name: Publish Docker Image

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "alpine.Dockerfile"
      - ".github/workflows/publish-image.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "alpine.Dockerfile"
      - ".github/workflows/publish-image.yaml"

jobs:
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            tag: latest
            sha_prefix: ""
          - dockerfile: alpine.Dockerfile
            tag: alpine
            sha_prefix: "alpine-"
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Run docker/login-action
        if: github.event_name != 'pull_request'
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: sha
        run: echo "short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Run docker/build-push-action
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ matrix.tag }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ matrix.sha_prefix }}${{ steps.sha.outputs.short }}
